### PR TITLE
💚 Fix MongoDB url for wendy

### PR DESCRIPTION
**Pull request by grdryn**

### CODE REVIEW

**Comment by grdryn** [comment]
@sedroche this gets it a bit further, but not quite there yet. Let's take a look at this tomorrow.

**Comment by sedroche** [comment]
@grdryn I have updated this PR with some changes to make our test suite pass when run against 3.x mongo. Can you run the wendy job when you get a chance and see how it goes?

**Comment by grdryn** [comment]
@sedroche there still appears to be a test failure: https://jenkins-wendy.ci.feedhenry.org/job/feedhenry/job/fh-dataman/job/PR-44/3/console

I'll try to make it so that you can trigger the job yourself.

**Review by rachael-oregan — APPROVED** [review]
LGTM

**Review by pb82 — APPROVED** [review]
LGTM. So the test was failing because Wendy runs Mongo3 and there were system collections that we didn't expect?

**Comment by sedroche** [comment]
@pb82  Yes. I suppose it's not mongo 3 but more that mongo instance on wendy had extra system collections. I am filtering all documented system collections now.
We also needed to point to the mongo instance on wendy

**Pull request merged**
